"""Enrich raw ValidationIssue objects with human labels and translations.

Two side-loaded maps:

1. feldkennung_map.json — Feldidentifikator → German label, keyed by datenartVersion.
   Generated by ug_steuer.feldkennung_extractor from the ERiC
   Schnittstellenbeschreibungen schemas. Bake into the Docker image.

2. error_translations.json — error/hinweis code → user-friendly German message.
   Hand-curated. Starts empty. Every untranslated code that comes through is
   logged to a "needs translation" queue so the maintainer can triage weekly.

Both files are optional. If neither is present, enrichment is a no-op and
the raw ERiC text falls through to the user. The whole point is to make
ELSTER's cryptic Plausibilitätsfehler readable — but we're never worse off
than ELSTER itself if a label is missing.
"""

from __future__ import annotations

import json
import logging
import threading
from dataclasses import dataclass, field
from pathlib import Path

from .eric import ValidationIssue

logger = logging.getLogger(__name__)


@dataclass
class IssueEnricher:
    """Loads the maps once and applies them to ValidationIssue lists.

    Thread-safe. Designed to live as a process-level singleton in the
    sidecar; load on startup, reuse forever.
    """

    feldkennung_map_path: Path | None = None
    error_translations_path: Path | None = None
    queue_path: Path | None = None  # JSONL of unknown codes for triage

    _feldkennung: dict[str, dict[str, str]] = field(default_factory=dict)
    _translations: dict[str, str] = field(default_factory=dict)
    _seen_unknown: set[str] = field(default_factory=set)
    _lock: threading.Lock = field(default_factory=threading.Lock)

    def load(self) -> None:
        """Load both maps from disk. Missing files are tolerated."""
        if self.feldkennung_map_path and self.feldkennung_map_path.is_file():
            try:
                with self.feldkennung_map_path.open(encoding="utf-8") as f:
                    self._feldkennung = json.load(f)
                total = sum(len(v) for v in self._feldkennung.values())
                logger.info(
                    "Loaded feldkennung map: %d datenarts, %d fields",
                    len(self._feldkennung), total,
                )
            except Exception as e:
                logger.warning("Failed to load feldkennung map: %s", e)
                self._feldkennung = {}
        else:
            logger.info("No feldkennung map at %s — field labels disabled",
                        self.feldkennung_map_path)

        if self.error_translations_path and self.error_translations_path.is_file():
            try:
                with self.error_translations_path.open(encoding="utf-8") as f:
                    self._translations = json.load(f)
                logger.info("Loaded error translations: %d entries", len(self._translations))
            except Exception as e:
                logger.warning("Failed to load error translations: %s", e)
                self._translations = {}
        else:
            logger.info("No error translations at %s — using raw ERiC text",
                        self.error_translations_path)

    def enrich(self, issues: list[ValidationIssue], datenart_version: str) -> list[ValidationIssue]:
        """Apply field labels and translations in place. Returns the same list."""
        bucket = self._feldkennung.get(datenart_version, {})
        for issue in issues:
            if issue.feldkennung and not issue.field_label:
                # Try the exact feldkennung first.
                label = bucket.get(issue.feldkennung)
                if label is None and "/" in issue.feldkennung:
                    # E-Bilanz-style XPath identifiers — try the last segment.
                    leaf = issue.feldkennung.rsplit("/", 1)[-1]
                    label = bucket.get(leaf)
                if label is None and "[" in issue.feldkennung:
                    # Strip array index suffixes like "Foo[1]"
                    bare = issue.feldkennung.split("[", 1)[0]
                    label = bucket.get(bare)
                if label:
                    issue.field_label = label

            if issue.code:
                translation = self._translations.get(issue.code)
                if translation:
                    issue.human_message = translation
                elif issue.severity == "error":
                    self._record_unknown(issue, datenart_version)

        return issues

    def _record_unknown(self, issue: ValidationIssue, datenart_version: str) -> None:
        """Append unknown error code to the triage queue (idempotent per process)."""
        if not self.queue_path or not issue.code:
            return
        key = f"{datenart_version}:{issue.code}"
        with self._lock:
            if key in self._seen_unknown:
                return
            self._seen_unknown.add(key)
            try:
                self.queue_path.parent.mkdir(parents=True, exist_ok=True)
                with self.queue_path.open("a", encoding="utf-8") as f:
                    f.write(json.dumps({
                        "datenart": datenart_version,
                        "code": issue.code,
                        "feldkennung": issue.feldkennung,
                        "field_label": issue.field_label,
                        "message_de": issue.message_de[:500],
                        "regel_name": issue.regel_name,
                    }, ensure_ascii=False) + "\n")
            except Exception as e:
                logger.warning("Failed to record unknown error code: %s", e)
